### ISSUE TITLE
hardcoded queries

### ISSUE THREAD

**Issue by SebastianPozoga** [goatcms/goatcms#1]
https://github.com/goatcms/goatcms/blob/master/services/database/main.go

It contains hardcoded queries. It should be in separated files. 

I recomend:
- create new directory database for fixtures, sql files etc
- and create file ./schema to contains table create code

**Comment by s3c0nDD** [comment]
what is status of this issue?

**Comment by SebastianPozoga** [comment]
It is done. Now all queries are generated by dsql and it is storage into orm.Table object.

dsql https://github.com/goatcms/goat-core/tree/dev/db/dsql
https://github.com/goatcms/goat-core/blob/dev/db/orm/table.go
